name = "recoil"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "recoil-db"
database_id = "2f09d44b-0d1b-450d-a805-f0aab170b2b7"

[[r2_buckets]]
binding = "R2"
bucket_name = "recoil-files"

[vars]
APP_ENV = "production"
